# note that 'ports' makes these services available to the host on hostpost:containerport
# later we will want to keep them private via docker 'expose' and just publish specific container ports with 'ports'

services:
  stat_server_py:
    build: ./stat_server_py
    ports:
      - "8000:8000"
    depends_on:
      - hapi


  stat_server_r:
    build: ./stat_server_r
    ports:
      - "8001:8000"
    depends_on:
      - hapi


  hapi:
    container_name: hapi
    image: "hapiproject/hapi:latest"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
    depends_on:
      - hapi_db


  hapi_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    volumes:
      - ./hapi/postgres_data:/var/lib/postgresql/data


  synthea_server:
    depends_on:
      - hapi
    build: ./synthea_server
    ports:
      - "8002:8000"


  model_server:
    depends_on:
      - mongo_model_server
    build: ./model_server
    ports:
      - "8003:8000"
    volumes:
      - shared_tmp:/shared-tmp
      - /var/run/docker.sock:/var/run/docker.sock


  mongo_model_server:
    image: mongo:6
    restart: always
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db


configs:
  hapi:
    file: ./hapi/hapi.application.yaml


# shared_tmp is used by the model server to share files with spun-up model containers; do not remove
volumes:
  shared_tmp:
  mongo_data: